-- ============================================================================
-- PraShree Arts — Vastu placement compass (generated by scripts/generate-vastu-sql.mjs)
-- Run AFTER 20260820_artworks.sql. Idempotent and re-runnable.
-- All copy below is DRAFT pending Monica's confirmation; edit it at /admin.
-- ============================================================================

-- ── Placement fields on artworks ──
ALTER TABLE products ADD COLUMN IF NOT EXISTS secondary_direction TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS placement_note      VARCHAR(140);
ALTER TABLE products ADD COLUMN IF NOT EXISTS placement_detail    TEXT;

-- direction is a pre-existing column: NOT VALID skips checking current rows
-- (they all come from the admin select or items.json) but guards every write
-- from now on. secondary_direction is new, so it validates fully.
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_direction_check;
ALTER TABLE products ADD CONSTRAINT products_direction_check
  CHECK (direction IS NULL OR direction IN ('North', 'North-East', 'East', 'South-East', 'South', 'South-West', 'West', 'North-West', 'Centre')) NOT VALID;
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_secondary_direction_check;
ALTER TABLE products ADD CONSTRAINT products_secondary_direction_check
  CHECK (secondary_direction IS NULL OR secondary_direction IN ('North', 'North-East', 'East', 'South-East', 'South', 'South-West', 'West', 'North-West', 'Centre'));

CREATE INDEX IF NOT EXISTS idx_products_direction           ON products(direction);
CREATE INDEX IF NOT EXISTS idx_products_secondary_direction ON products(secondary_direction);

-- ── Direction profiles: the wheel's own copy, one row per direction ──
CREATE TABLE IF NOT EXISTS vastu_direction_profiles (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  direction      TEXT NOT NULL UNIQUE
                   CHECK (direction IN ('North', 'North-East', 'East', 'South-East', 'South', 'South-West', 'West', 'North-West', 'Centre')),
  label          TEXT NOT NULL,                 -- 'North', 'North-East'
  sanskrit_name  TEXT,                          -- Uttara, Ishanya …
  guardian       TEXT,                          -- traditional presiding figure
  element        TEXT,
  essence        TEXT NOT NULL,                 -- three to five words for the wheel rim
  description    TEXT NOT NULL,                 -- two or three sentences for the reading panel
  sort_order     INTEGER NOT NULL DEFAULT 0,    -- clockwise from North; Centre last
  shows_artworks BOOLEAN NOT NULL DEFAULT TRUE, -- FALSE for Brahmasthana (kept uncrowded)
  edited_at      TIMESTAMPTZ,                   -- set by /admin; seed skips edited rows
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_vastu_direction_profiles_updated_at ON vastu_direction_profiles;
CREATE TRIGGER trg_vastu_direction_profiles_updated_at
  BEFORE UPDATE ON vastu_direction_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER TABLE vastu_direction_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read vastu profiles" ON vastu_direction_profiles;
CREATE POLICY "Public read vastu profiles" ON vastu_direction_profiles
  FOR SELECT USING (true);
DROP POLICY IF EXISTS "Authenticated insert on vastu profiles" ON vastu_direction_profiles;
CREATE POLICY "Authenticated insert on vastu profiles" ON vastu_direction_profiles
  FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Authenticated update on vastu profiles" ON vastu_direction_profiles;
CREATE POLICY "Authenticated update on vastu profiles" ON vastu_direction_profiles
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Authenticated delete on vastu profiles" ON vastu_direction_profiles;
CREATE POLICY "Authenticated delete on vastu profiles" ON vastu_direction_profiles
  FOR DELETE TO authenticated USING (true);

-- ── Seed the nine profiles (draft copy; rows edited in /admin are untouched) ──
INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('North', 'North', 'Uttara', 'Kubera', 'Water',
   'Flow and prosperity',
   'In Vastu tradition the north is Kubera''s quarter, associated with flow and the keeping of what one has. A north wall suits a piece that feels open and moving rather than heavy. Living rooms and entrances often turn this way.',
   1, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('North-East', 'North-East', 'Ishanya', 'Shiva', 'Water',
   'Stillness and prayer',
   'Ishanya is held to be the most sacred corner of a home, kept light, clean and quiet. Tradition places prayer and meditation here. Choose work that asks for stillness and rewards a long look.',
   2, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('East', 'East', 'Purva', 'Indra / Surya', 'Air',
   'Clarity and beginnings',
   'The east receives the first light, and tradition reads it as the direction of beginnings and clear thinking. It suits a study, a desk wall, or wherever the day starts. Pieces with a bright, open centre sit naturally here.',
   3, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('South-East', 'South-East', 'Agneya', 'Agni', 'Fire',
   'Warmth and transformation',
   'Agneya is the fire corner, traditionally the kitchen''s place. It carries warmth, appetite and change. Work with movement and energy belongs here, in a spot that catches attention rather than one that invites rest.',
   4, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('South', 'South', 'Dakshina', 'Yama', 'Earth',
   'Structure and resolve',
   'The south is read as steady and disciplined in Vastu tradition, a direction of resolve. It suits pieces with strong structure and a firm outline. A south wall can carry visual weight that would crowd a lighter room.',
   5, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('South-West', 'South-West', 'Nairutya', 'Nairuti', 'Earth',
   'Weight and steadiness',
   'Nairutya is traditionally the heaviest corner of a home, the one that anchors the rest. Bedrooms and stores are often placed here. Grounded, protective compositions feel at home on a south-west wall.',
   6, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('West', 'West', 'Paschima', 'Varuna', 'Water',
   'Rest and completion',
   'The west holds the setting sun and, in tradition, the sense of a day drawing to a close. It suits the rooms a household settles into in the evening. Calm, flowing work belongs here more than anything restless.',
   7, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('North-West', 'North-West', 'Vayavya', 'Vayu', 'Air',
   'Movement and welcome',
   'Vayavya is the corner of wind and movement, traditionally given to guests and to things that come and go. Entrance halls and guest rooms often face this way. Choose pieces that feel welcoming and light.',
   8, TRUE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

INSERT INTO vastu_direction_profiles
  (direction, label, sanskrit_name, guardian, element, essence, description, sort_order, shows_artworks)
VALUES
  ('Centre', 'Centre', 'Brahmasthana', 'Brahma', 'Space',
   'Openness, kept clear',
   'The Brahmasthana is the open heart of a home, and tradition holds that it should stay uncrowded. Nothing is recommended for hanging here. Let the walls around it carry the work and keep the centre clear.',
   9, FALSE)
ON CONFLICT (direction) DO UPDATE SET
  label = EXCLUDED.label, sanskrit_name = EXCLUDED.sanskrit_name,
  guardian = EXCLUDED.guardian, element = EXCLUDED.element,
  essence = EXCLUDED.essence, description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order, shows_artworks = EXCLUDED.shows_artworks
WHERE vastu_direction_profiles.edited_at IS NULL;

-- ── Backfill the draft artwork mappings (Appendix B minus the money line) ──
-- Only the three placement columns are written; the primary direction, and
-- every other catalogue field, is owned by 20260820_artworks.sql.
UPDATE products SET
  secondary_direction = 'South-West',
  placement_note      = 'The heaviest corner of a home, traditionally the one that holds.',
  placement_detail    = NULL
WHERE slug = 'kavach';

UPDATE products SET
  secondary_direction = 'East',
  placement_note      = 'For a study or desk wall that catches the morning.',
  placement_detail    = NULL
WHERE slug = 'sarasvati';

UPDATE products SET
  secondary_direction = 'West',
  placement_note      = 'For the wall a room settles into at the end of the day.',
  placement_detail    = NULL
WHERE slug = 'svadhisthana';

UPDATE products SET
  secondary_direction = 'North',
  placement_note      = 'Sits well in a prayer space or above a home shrine.',
  placement_detail    = NULL
WHERE slug = 'mahadeva';

UPDATE products SET
  secondary_direction = NULL,
  placement_note      = 'Made for the corner of a home that stays quiet.',
  placement_detail    = NULL
WHERE slug = 'dhyana';

UPDATE products SET
  secondary_direction = 'North-West',
  placement_note      = 'Entrance halls and guest rooms — the directions of arrival.',
  placement_detail    = NULL
WHERE slug = 'ananda';
