-- ============================================================================
-- PraShree Arts — artworks catalogue (generated by scripts/generate-artworks-sql.mjs)
-- Run AFTER schema.sql + 20260819_refactor.sql. Idempotent: upserts by slug.
-- ============================================================================

-- Catalogue columns for the artworks data
ALTER TABLE products ADD COLUMN IF NOT EXISTS size        TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS size_code   TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price_range TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS usd         TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS prints      TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS hours       TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS series      TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS form        TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS intent      TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS direction   TEXT;

CREATE INDEX IF NOT EXISTS idx_products_form      ON products(form);
CREATE INDEX IF NOT EXISTS idx_products_series    ON products(series);
CREATE INDEX IF NOT EXISTS idx_products_size_code ON products(size_code);
CREATE INDEX IF NOT EXISTS idx_products_price     ON products(price);

-- Remove the Phase-3 placeholder seeds (superseded by the real catalogue)
DELETE FROM products WHERE slug LIKE 'sample-%';

-- Upsert the catalogue
INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Aditya · Sunflower of Joy', 'aditya', 'Joy, positivity & new beginnings', 8500,
   ARRAY['/images/products/thumbs/aditya.jpg'],
   '/catalogues/Aditya-SunflowerOfJoy_2page.pdf',
   'Primary Vastu direction: East',
   '24 × 17 cm', '24×17', '₹7,000–10,000', 'USD 84–120', '₹800–1,600',
   '28–40 hrs', 'Joy & Positivity Series', 'Mandala Art', 'Joy, positivity & new beginnings', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Anahata · Flower of Life', 'anahata', 'Love, connection & harmony', 8500,
   ARRAY['/images/products/thumbs/anahata.jpg'],
   '/catalogues/Anahata-FlowerOfLife_2page.pdf',
   'Primary Vastu direction: South-West',
   '24 × 17 cm', '24×17', '₹7,000–10,000', 'USD 84–120', '₹800–1,600',
   '28–40 hrs', 'Love & Connection Series', 'Mandala Art', 'Love, connection & harmony', 'South-West',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Chakra · Wheel of Change', 'chakra', 'Transformation, flow & positive change', 8500,
   ARRAY['/images/products/thumbs/chakra.jpg'],
   '/catalogues/Chakra-WheelOfChange_2page.pdf',
   'Primary Vastu direction: North-West',
   '24 × 17 cm', '24×17', '₹7,000–10,000', 'USD 84–120', '₹800–1,600',
   '28–40 hrs', 'Transformation & Flow Series', 'Mandala Art', 'Transformation, flow & positive change', 'North-West',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Kavach · Shield of Focus', 'kavach', 'Focus, protection & grounding', 8500,
   ARRAY['/images/products/thumbs/kavach.jpg'],
   '/catalogues/Kavach-ShieldOfFocus_2page.pdf',
   'Primary Vastu direction: North',
   '24 × 17 cm', '24×17', '₹7,000–10,000', 'USD 84–120', '₹800–1,600',
   '28–40 hrs', 'Focus & Protection Series', 'Mandala Art', 'Focus, protection & grounding', 'North',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Lakshmi Bloom', 'lakshmi', 'Abundance & prosperity', 7000,
   ARRAY['/images/products/thumbs/lakshmi.jpg'],
   '/catalogues/Lakshmi-Bloom_2page.pdf',
   'Primary Vastu direction: North',
   '17 × 24 cm', '17×24', '₹6,000–8,500', 'USD 72–102', '₹700–1,500',
   '22–30 hrs', 'Money Manifestation Series', 'Mandala Art', 'Abundance & prosperity', 'North',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Sarasvati · Lotus of Wisdom', 'sarasvati', 'Creativity, wisdom & learning', 8500,
   ARRAY['/images/products/thumbs/sarasvati.jpg'],
   '/catalogues/Sarasvati-LotusOfWisdom_2page.pdf',
   'Primary Vastu direction: North-East',
   '24 × 17 cm', '24×17', '₹7,000–10,000', 'USD 84–120', '₹800–1,600',
   '28–40 hrs', 'Wisdom & Creativity Series', 'Mandala Art', 'Creativity, wisdom & learning', 'North-East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Shanti · Bloom of Peace', 'shanti', 'Peace, harmony & healing', 8500,
   ARRAY['/images/products/thumbs/shanti.jpg'],
   '/catalogues/Shanti-BloomOfPeace_2page.pdf',
   'Primary Vastu direction: North-East',
   '24 × 17 cm', '24×17', '₹7,000–10,000', 'USD 84–120', '₹800–1,600',
   '28–40 hrs', 'Peace & Harmony Series', 'Mandala Art', 'Peace, harmony & healing', 'North-East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Tejas · Radiant Star', 'tejas', 'Spiritual energy & vitality', 8500,
   ARRAY['/images/products/thumbs/tejas.jpg'],
   '/catalogues/Tejas-RadiantStar_2page.pdf',
   'Primary Vastu direction: East',
   '24 × 17 cm', '24×17', '₹7,000–10,000', 'USD 84–120', '₹800–1,600',
   '28–40 hrs', 'Spiritual Energy Series', 'Mandala Art', 'Spiritual energy & vitality', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Manipura · Spiral of Energy', 'manipura', 'Energy, momentum & personal power', 15000,
   ARRAY['/images/products/thumbs/manipura.jpg'],
   '/catalogues/Manipura-SpiralOfEnergy_2page.pdf',
   'Primary Vastu direction: South-East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Energy & Momentum Series', 'Geometric & Op Art', 'Energy, momentum & personal power', 'South-East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Sahasrara · Lotus of Bliss', 'sahasrara', 'Joy, wisdom & inner peace', 15000,
   ARRAY['/images/products/thumbs/sahasrara.jpg'],
   '/catalogues/Sahasrara-LotusOfBliss_2page.pdf',
   'Primary Vastu direction: North-East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Peace & Wisdom Series', 'Mandala Art', 'Joy, wisdom & inner peace', 'North-East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Padma · Bloom of Abundance', 'padma', 'Abundance, growth & good fortune', 15000,
   ARRAY['/images/products/thumbs/padma.jpg'],
   '/catalogues/Padma-BloomOfAbundance_2page.pdf',
   'Primary Vastu direction: North',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Prosperity & Growth Series', 'Mandala Art', 'Abundance, growth & good fortune', 'North',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Svadhisthana · Lotus of Flow', 'svadhisthana', 'Creativity, flow & emotional balance', 15000,
   ARRAY['/images/products/thumbs/svadhisthana.jpg'],
   '/catalogues/Svadhisthana-LotusOfFlow_2page.pdf',
   'Primary Vastu direction: East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Creativity & Flow Series', 'Mandala Art', 'Creativity, flow & emotional balance', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Muladhara · Woven Shield', 'muladhara', 'Stability, protection & grounding', 15000,
   ARRAY['/images/products/thumbs/muladhara.jpg'],
   '/catalogues/Muladhara-WovenShield_2page.pdf',
   'Primary Vastu direction: South-West',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Grounding & Protection Series', 'Mandala Art', 'Stability, protection & grounding', 'South-West',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Ajna · Lotus of Clarity', 'ajna', 'Clarity, focus & balanced judgement', 15000,
   ARRAY['/images/products/thumbs/ajna.jpg'],
   '/catalogues/Ajna-LotusOfClarity_2page.pdf',
   'Primary Vastu direction: North-East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Clarity & Focus Series', 'Mandala Art', 'Clarity, focus & balanced judgement', 'North-East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Vishuddha · Radiant Voice', 'vishuddha', 'Expression, confidence & clear communication', 15000,
   ARRAY['/images/products/thumbs/vishuddha.jpg'],
   '/catalogues/Vishuddha-RadiantVoice_2page.pdf',
   'Primary Vastu direction: North-West',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Expression & Confidence Series', 'Abstract Line Art', 'Expression, confidence & clear communication', 'North-West',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Mahadeva · Crescent of Stillness', 'mahadeva', 'Inner strength, protection & transformation', 15000,
   ARRAY['/images/products/thumbs/mahadeva.jpg'],
   '/catalogues/Mahadeva-CrescentOfStillness_2page.pdf',
   'Primary Vastu direction: North-East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Devotion & Strength Series', 'Figurative & Devotional Art', 'Inner strength, protection & transformation', 'North-East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Pushpa · Garden of Joy', 'pushpa', 'Joy, positivity & fresh beginnings', 15000,
   ARRAY['/images/products/thumbs/pushpa.jpg'],
   '/catalogues/Pushpa-GardenOfJoy_2page.pdf',
   'Primary Vastu direction: East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Joy & Blossom Series', 'Botanical & Floral Art', 'Joy, positivity & fresh beginnings', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Tarang · Waves of Courage', 'tarang', 'Courage, momentum & bold change', 15000,
   ARRAY['/images/products/thumbs/tarang.jpg'],
   '/catalogues/Tarang-WavesOfCourage_2page.pdf',
   'Primary Vastu direction: South',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Courage & Movement Series', 'Abstract Line Art', 'Courage, momentum & bold change', 'South',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Patra · The Monstera Leaf', 'patra', 'Growth, calm & natural balance', 15000,
   ARRAY['/images/products/thumbs/patra.jpg'],
   '/catalogues/Patra-TheMonsteraLeaf_2page.pdf',
   'Primary Vastu direction: East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Nature & Growth Series', 'Botanical & Floral Art', 'Growth, calm & natural balance', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Kubera · Rivers of Wealth', 'kubera', 'Wealth, abundance & financial flow', 15000,
   ARRAY['/images/products/thumbs/kubera.jpg'],
   '/catalogues/Kubera-RiversOfWealth_2page.pdf',
   'Primary Vastu direction: North',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Wealth & Manifestation Series', 'Money Manifestation Art', 'Wealth, abundance & financial flow', 'North',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Dhyana · Seat of Balance', 'dhyana', 'Balance, meditation & inner harmony', 15000,
   ARRAY['/images/products/thumbs/dhyana.jpg'],
   '/catalogues/Dhyana-SeatOfBalance_2page.pdf',
   'Primary Vastu direction: North-East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Balance & Harmony Series', 'Figurative & Devotional Art', 'Balance, meditation & inner harmony', 'North-East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Jaala · Web of Connection', 'jaala', 'Connection, community & belonging', 15000,
   ARRAY['/images/products/thumbs/jaala.jpg'],
   '/catalogues/Jaala-WebOfConnection_2page.pdf',
   'Primary Vastu direction: North-West',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Connection & Unity Series', 'Abstract Line Art', 'Connection, community & belonging', 'North-West',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Vana · Canopy of Leaves', 'vana', 'Renewal, freshness & quiet abundance', 15000,
   ARRAY['/images/products/thumbs/vana.jpg'],
   '/catalogues/Vana-CanopyOfLeaves_2page.pdf',
   'Primary Vastu direction: North',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Nature & Renewal Series', 'Botanical & Floral Art', 'Renewal, freshness & quiet abundance', 'North',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Sevanti · Field of Daisies', 'sevanti', 'Cheer, gratitude & simple abundance', 15000,
   ARRAY['/images/products/thumbs/sevanti.jpg'],
   '/catalogues/Sevanti-FieldOfDaisies_2page.pdf',
   'Primary Vastu direction: East',
   'A3 · 29.7 × 42 cm', 'A3', '₹12,000–18,000', 'USD 145–215', '₹1,500–3,000',
   '30–45 hrs', 'Joy & Blossom Series', 'Botanical & Floral Art', 'Cheer, gratitude & simple abundance', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Surya · Sun of Vitality', 'surya', 'Vitality, warmth & good health', 4500,
   ARRAY['/images/products/thumbs/surya.jpg'],
   '/catalogues/Surya-SunOfVitality_A5_2page.pdf',
   'Primary Vastu direction: East',
   'A5 · 14.8 × 21 cm', 'A5', '₹3,500–6,000', 'USD 42–72', '₹500–1,000',
   '12–18 hrs', 'Vitality & Light Series', 'Mandala Art', 'Vitality, warmth & good health', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Ananda · Smile of Contentment', 'ananda', 'Happiness, contentment & a warm home', 6500,
   ARRAY['/images/products/thumbs/ananda.jpg'],
   '/catalogues/Ananda-SmileOfContentment_B5_2page.pdf',
   'Primary Vastu direction: East',
   'B5 · 17.6 × 25 cm', 'B5', '₹5,000–8,000', 'USD 60–95', '₹700–1,400',
   '16–24 hrs', 'Joy & Wisdom Series', 'Mandala Art', 'Happiness, contentment & a warm home', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;

INSERT INTO products
  (name, slug, description, price, images, pdf_url, vastu_note,
   size, size_code, price_range, usd, prints, hours, series, form, intent, direction,
   is_featured, is_available)
VALUES
  ('Pravaha · The Crossing', 'pravaha', 'Transition, resilience & finding your path', 6500,
   ARRAY['/images/products/thumbs/pravaha.jpg'],
   '/catalogues/Pravaha-TheCrossing_B5_2page.pdf',
   'Primary Vastu direction: East',
   'B5 · 17.6 × 25 cm', 'B5', '₹5,000–8,000', 'USD 60–95', '₹700–1,400',
   '16–24 hrs', 'Journey & Transformation Series', 'Abstract Line Art', 'Transition, resilience & finding your path', 'East',
   FALSE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price,
  images = EXCLUDED.images, pdf_url = EXCLUDED.pdf_url, vastu_note = EXCLUDED.vastu_note,
  size = EXCLUDED.size, size_code = EXCLUDED.size_code, price_range = EXCLUDED.price_range,
  usd = EXCLUDED.usd, prints = EXCLUDED.prints, hours = EXCLUDED.hours,
  series = EXCLUDED.series, form = EXCLUDED.form, intent = EXCLUDED.intent,
  direction = EXCLUDED.direction, is_available = TRUE;
